- name: "Stage 3. add postgresql roles"
  postgresql_user:
    state: present
    name: "{{ item.name }}"
    encrypted: yes
    password: "{{ item.pass }}"
    role_attr_flags: "{{ item.flags }}"
  with_items: "{{ postgresql_users }}"
  when: postgresql_users|length > 0
